# Generated by Django 5.0.6 on 2024-05-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='img',
            field=models.ImageField(upload_to='mainapp/images', verbose_name='Изображение'),
        ),
    ]
